package infrastructure.network;

public enum CommandType {
    // Test
    PING,

    // Staff
    STAFF_LOGIN,
    STAFF_CREATE,
    STAFF_UPDATE,
    STAFF_FIND_BY_ID,
    STAFF_LOAD_ALL,

    // Product
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_FIND_BY_ID,
    PRODUCT_LOAD_ALL,

    // Invoice
    INVOICE_CREATE,
    INVOICE_FIND_BY_ID,
    INVOICE_LOAD_ALL,

    // Shift
    SHIFT_CREATE,
    SHIFT_UPDATE,
    SHIFT_FIND_BY_ID,
    SHIFT_GET_ACTIVE,

    // Lot
    LOT_CREATE,
    LOT_UPDATE,
    LOT_FIND_BY_ID,
    LOT_LOAD_ALL,

    // Customer
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_FIND_BY_ID,
    CUSTOMER_FIND_BY_PHONE,

    // Promotion
    PROMOTION_CREATE,
    PROMOTION_SET_ACTIVE,
    PROMOTION_FIND_BY_ID,
    PROMOTION_LOAD_ALL,
    PROMOTION_LOAD_ACTIVE,

    // Measurement
    MEASUREMENT_FIND_BY_ID,
    MEASUREMENT_LOAD_ALL;
}